name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore /home/runner/work/DevOps/DevOps/MicroService/MicroService.csproj
    - name: Build
      run: dotnet build /home/runner/work/DevOps/DevOps/MicroService/MicroService.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test /home/runner/work/DevOps/DevOps/Test.DevOps/Test.DevOps.csproj --no-restore --verbosity normal
    - name: dotnet publish
      run: dotnet publish /home/runner/work/DevOps/DevOps/MicroService/MicroService.csproj -c Release -o microservice
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
          app-name: devopstestrogerachig
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
          package: './DevOps'
